"use client"

import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Navbar from "@/components/common/Navbar";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/context/Auth";

// const inter = Inter({ subsets: ["latin"] });

// this cannot be used with "use client"
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex flex-col h-screen items-center'>
        <AntdRegistry>
          <AuthProvider>
            <Toaster position="top-center" />
            <Navbar />
            {children}
          </AuthProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
